import "~/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav(){
return (
 <nav className="flex items-center justify-between w-full p-4 text-x1 font-semibold border-b text-blue-700" >
  <div>MTC Export</div>
  <div>Importacion</div>
  <div>Exportacion</div>
  <div>Administracion</div>
  <div>Sign in</div>
 </nav>
);
}

function SideBar(){
return (
 <nav className="flex items-center justify-between w-full p-4 text-x1 font-semibold border-b text-blue-700" >
  <div>MTC Export</div>

  <div>Sign in</div>
 </nav>
);
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} flex flex-col gap-4`}>
      <TopNav></TopNav>
      </body>
    </html>
  );
}
